FROM nvcr.io/nvidia/cuda:11.8.0-devel-ubuntu22.04

RUN apt-get update  && apt-get install -y git python3-virtualenv wget 

RUN pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

RUN pip3 install -U --no-cache-dir git+https://github.com/facebookresearch/llama-recipes.git@main

WORKDIR /workspace
# Setup server requriements

COPY ./fast_api_requirements.txt fast_api_requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r fast_api_requirements.txt

COPY ./requirements.txt requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

ENV HUGGINGFACE_TOKEN="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"
ENV HUGGINGFACE_BASE_REPO="Qwen/Qwen-14B"
ENV HUGGINGFACE_ADAPTER_REPO="jiangchensiat/submission_4090_03_adapter"

# Copy over single file server
COPY ./main.py main.py
COPY ./api.py api.py

COPY ./cache.py cache.py
RUN python3 cache.py

# Run the server
CMD ["python3", "main.py"]
