FROM nvcr.io/nvidia/pytorch:22.12-py3
RUN apt-get update  && apt-get install -y git python3-virtualenv wget
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash \
    && apt-get install git-lfs \
    && git lfs install

WORKDIR /workspace

RUN git clone https://github.com/zhuwenxi/llm_finetuning.git

WORKDIR llm_finetuning
RUN pip install -r requirements.txt \
    && pip install -r cuda_quant_requirements.txt
