import logging
import tempfile
import pathlib as plb

import typer
import yaml
import sh

from cajajejo.utils import yaml_str_presenter
from cajajejo.config import TrainingConfig
from .utils import (
    validate_config,
    parse_training_job_and_write_to_file,
)

yaml.add_representer(str, yaml_str_presenter)
yaml.representer.SafeRepresenter.add_representer(str, yaml_str_presenter)

logger = logging.getLogger("cajajejo.commands.jobs.training")

training_cmd = typer.Typer(
    help="💪 Commands for deploying training jobs",
    no_args_is_help=True,
)


@training_cmd.command(
    name="validate-job-config",
    help="✅ Validate a training job configuration file.",
    short_help="✅ Validate a training job configuration file.",
    no_args_is_help=True,
)
def _validate_config(
    path_to_config: str = typer.Argument(None, help="Path to a training config file.")
):
    validate_config(path_to_config, TrainingConfig)


@training_cmd.command(
    name="parse-job",
    help="✍ Parse a kubernetes training job using the training job config file.",
    short_help="✍ Parse a kubernetes training job using the training job config file.",
    no_args_is_help=True,
)
def _parse_job(
    path_to_config: str = typer.Argument(None, help="Path to a training config file."),
    job_spec_output_path: str = typer.Argument(
        None, help="Path to which the job spec should be written."
    ),
    config_version: str = typer.Option(
        None,
        help="Version of the training config file. This can be any string, for example a GIT commit hash.",
    ),
):
    parse_training_job_and_write_to_file(
        path_to_config=path_to_config,
        job_spec_output_path=job_spec_output_path,
        config_version=config_version,
    )


@training_cmd.command(
    name="submit-job",
    short_help="🙏 Submit a kubernetes training job.",
    help="""🙏 Submit a kubernetes training job. You must either pass a job spec
    (generated by `cajajejo jobs training parse-job`) or an training config file,
    a helm config path, and a job template path. This will generate the kubernetes
    job spec on the fly (optionally writing it to a location).""",
    no_args_is_help=True,
)
def _submit_job(
    path_to_config: str = typer.Option(None, help="Path to a training config file."),
    job_spec_output_path: str = typer.Option(
        None, help="Path to which the job spec should be written. Can be omitted."
    ),
    job_spec_path: str = typer.Option(
        None,
        help="Path to the job spec to use. If not defined, you must use `job_template_path` to generate the job spec.",
    ),
    config_version: str = typer.Option(
        None,
        help="Version of the evaluation config file. This can be any string, for example a GIT commit hash.",
    ),
):
    if job_spec_path is None:
        if path_to_config is None:
            raise ValueError(
                "You must either pass a job spec or an evaluation config file, a helm config path, and a job template path."
            )
    if job_spec_path is None:
        with tempfile.TemporaryDirectory() as tmpdir:
            if job_spec_output_path is None:
                job_spec_output_path = str(plb.Path(tmpdir) / "job_spec.yaml")
            parse_training_job_and_write_to_file(
                path_to_config=path_to_config,
                job_spec_output_path=job_spec_output_path,
                config_version=config_version,
            )
            print(sh.kubectl.apply(["-f", job_spec_output_path]))
    else:
        print(sh.kubectl.apply(["-f", job_spec_path]))
    logger.info("🚀 Job submitted.")
