site_name: 'Neurips-llm-efficiency-challenge'
repo_url: 'https://github.com/godatadriven/neurips-llm-efficiency-challenge'

nav:
  - Home: index.md
  - Usage: usage.ipynb
  - API: cajajejo.md
  - Infrastructure: infrastructure.md
  - "Data versioning": data_versioning.md
  - Jobs: jobs.md
  - "Using local models with HELM": helm_local_models.md
  - Contributing: contributing.md
  - Conduct: conduct.md

theme:
  name: "material"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings
- include-markdown
- mkdocs-jupyter
