version: v1
image: europe-west4-docker.pkg.dev/neurips-llm-eff-challenge-2023/container-registry-neurips-2023/evaluation
image_tag: latest
model: mistralai/Mistral-7B-v0.1
load_in_8bit: true
torch_dtype: bfloat16
tokenizer_config:
  use_fast: true
compute_config:
  accelerator: nvidia-tesla-a100
  cpu: "4"
  memory: "40Gi"
