version: v1
image: europe-west4-docker.pkg.dev/neurips-llm-eff-challenge-2023/container-registry-neurips-2023/evaluation
image_tag: latest
model: EleutherAI/pythia-410m #mistralai/Mistral-7B-v0.1
load_in_8bit: false
torch_dtype: float16
mlflow_artifact_config:
  mlflow_tracking_uri: http://10.164.0.15:5000
  run_id: daa2fb9f154f4d3ab9b0ca74d6dce40a
  artifact_path: checkpoint-900
  model_directory: artifacts/checkpoint-900
  download_directory: /scratch/pythia410m
tokenizer_config:
  use_fast: true
compute_config:
  accelerator: nvidia-tesla-t4
  cpu: "4"
  memory: "40Gi"
#huggingface_token_secret_name: projects/750004521723/secrets/JASPER-HUGGINGFACE-TOKEN/versions/1
