FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel

RUN apt-get update  && apt-get install -y git python3-virtualenv wget

RUN pip install -q -U git+https://github.com/huggingface/transformers.git
RUN pip install -q -U git+https://github.com/huggingface/peft.git
RUN pip install -q -U git+https://github.com/huggingface/accelerate.git
RUN pip install trl datasets



WORKDIR /workspace

ENV HUGGINGFACE_TOKEN="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"
ENV HUGGINGFACE_REPO="mirodavide/Mistral-neurips_dm"

COPY training/training_mistral.py ./

CMD [ "python", "training_mistral.py"]